UNBOXED_PRIMITIVE_VALUE_TYPE = "__prim_slot"
IO_CLASS = "IO"
OBJECT_CLASS = "Object"
INTEGER_CLASS = "Int"
BOOLEAN_CLASS = "Bool"
STRING_CLASS = "String"

BUILT_IN_CLASSES = [
	IO_CLASS,
	OBJECT_CLASS,
	INTEGER_CLASS,
	BOOLEAN_CLASS,
	STRING_CLASS
]

VOID_TYPE = "Void"

LOCAL_SELF_NAME = "__self"
INIT_CIL_SUFFIX = "_init"